"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.urls import reverse_lazy
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')


# Application definition

INSTALLED_APPS = [
    # Unfold admin theme — must precede django.contrib.admin so its templates
    # and AdminSite take priority.
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'store',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static/root assets with compression, caching and HTTP
    # range support. Must come right after SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.storefront',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.environ.get('DB_NAME', 'xeco_agency'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# collectstatic target for production (served by WhiteNoise).
STATIC_ROOT = BASE_DIR / 'staticfiles'

# The compiled React bundles reference root-level asset folders (/videos/,
# /images/, /_next/) by absolute path. Serving the static dir at the site root
# lets WhiteNoise handle those with caching + range support too.
WHITENOISE_ROOT = BASE_DIR / 'static'

# User-uploaded / media files.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # Compress assets but keep original filenames (the bundles hard-code
        # asset paths, so manifest hashing would break them).
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}


# Email — Gmail SMTP. Use a Google "App Password" (not your account password)
# for EMAIL_HOST_PASSWORD; 2FA must be enabled on the account.
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# Sender shown on the enquiry email; defaults to the authenticated Gmail account.
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
# Where contact-form submissions are delivered.
CONTACT_RECIPIENT_EMAIL = os.environ.get('CONTACT_RECIPIENT_EMAIL', EMAIL_HOST_USER)


# ---------------------------------------------------------------------------
# Unfold admin theme
# https://unfoldadmin.com/docs/
# ---------------------------------------------------------------------------
UNFOLD = {
    'SITE_TITLE': 'Al Rayan Admin',
    'SITE_HEADER': 'Al Rayan',
    'SITE_SUBHEADER': 'Cloth House — Store management',
    'SITE_SYMBOL': 'checkroom',  # Material Symbols icon used as a fallback mark.
    'SITE_LOGO': lambda request: static('images/logo.svg'),
    'SHOW_HISTORY': True,
    'SHOW_VIEW_ON_SITE': False,
    'THEME': None,  # let the user toggle light/dark.
    'DASHBOARD_CALLBACK': 'store.dashboard.dashboard_callback',
    'BORDER_RADIUS': '8px',
    'COLORS': {
        # Emerald palette — a premium, culturally fitting brand green.
        'primary': {
            '50': '236 253 245',
            '100': '209 250 229',
            '200': '167 243 208',
            '300': '110 231 183',
            '400': '52 211 153',
            '500': '16 185 129',
            '600': '5 150 105',
            '700': '4 120 87',
            '800': '6 95 70',
            '900': '6 78 59',
            '950': '2 44 34',
        },
    },
    'SIDEBAR': {
        'show_search': True,
        'show_all_applications': False,
        'navigation': [
            {
                'title': _('Overview'),
                'separator': False,
                'items': [
                    {
                        'title': _('Dashboard'),
                        'icon': 'dashboard',
                        'link': reverse_lazy('admin:index'),
                    },
                ],
            },
            {
                'title': _('Catalogue'),
                'separator': True,
                'items': [
                    {'title': _('Products'), 'icon': 'checkroom',
                     'link': reverse_lazy('admin:store_product_changelist')},
                    {'title': _('Variants'), 'icon': 'palette',
                     'link': reverse_lazy('admin:store_productvariant_changelist')},
                    {'title': _('Categories'), 'icon': 'category',
                     'link': reverse_lazy('admin:store_category_changelist')},
                    {'title': _('Fabrics'), 'icon': 'texture',
                     'link': reverse_lazy('admin:store_fabric_changelist')},
                    {'title': _('Seasons'), 'icon': 'sunny',
                     'link': reverse_lazy('admin:store_season_changelist')},
                    {'title': _('Colors'), 'icon': 'colorize',
                     'link': reverse_lazy('admin:store_color_changelist')},
                ],
            },
            {
                'title': _('Sales & Pricing'),
                'separator': True,
                'items': [
                    {'title': _('Discounts'), 'icon': 'sell',
                     'link': reverse_lazy('admin:store_discount_changelist')},
                    {'title': _('Shipping rates'), 'icon': 'local_shipping',
                     'link': reverse_lazy('admin:store_shippingrate_changelist')},
                    {'title': _('Store settings'), 'icon': 'tune',
                     'link': reverse_lazy('admin:store_storesetting_changelist')},
                ],
            },
            {
                'title': _('Orders'),
                'separator': True,
                'items': [
                    {'title': _('Orders'), 'icon': 'shopping_bag',
                     'link': reverse_lazy('admin:store_order_changelist'),
                     'badge': 'store.dashboard.pending_orders_badge'},
                    {'title': _('Carts'), 'icon': 'shopping_cart',
                     'link': reverse_lazy('admin:store_cart_changelist')},
                ],
            },
            {
                'title': _('Administration'),
                'separator': True,
                'items': [
                    {'title': _('Users'), 'icon': 'person',
                     'link': reverse_lazy('admin:auth_user_changelist')},
                    {'title': _('Groups'), 'icon': 'group',
                     'link': reverse_lazy('admin:auth_group_changelist')},
                ],
            },
        ],
    },
}
